# k8s/rbac/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- https://raw.githubusercontent.com/strimzi/strimzi-kafka-operator/0.46.0/install/cluster-operator/021-ClusterRole-strimzi-cluster-operator-role.yaml
- https://raw.githubusercontent.com/strimzi/strimzi-kafka-operator/0.46.0/install/cluster-operator/022-ClusterRoleBinding-strimzi-cluster-operator.yaml
- https://raw.githubusercontent.com/strimzi/strimzi-kafka-operator/0.46.0/install/cluster-operator/023-ClusterRole-strimzi-entity-operator-delegation.yaml
- https://raw.githubusercontent.com/strimzi/strimzi-kafka-operator/0.46.0/install/cluster-operator/024-ClusterRoleBinding-strimzi-entity-operator-delegation.yaml
- https://raw.githubusercontent.com/strimzi/strimzi-kafka-operator/0.46.0/install/cluster-operator/031-ClusterRole-strimzi-kafka-client.yaml

commonLabels:
  app.kubernetes.io/name: strimzi-operator
  app.kubernetes.io/component: rbac
  managed-by: argocd

# Patch ClusterRoleBindings to use correct ServiceAccount
patchesStrategicMerge:
- |-
  apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRoleBinding
  metadata:
    name: strimzi-cluster-operator
  subjects:
  - kind: ServiceAccount
    name: strimzi-cluster-operator
    namespace: kafka-system
